source "https://rubygems.org"

# Stay on Jekyll 4.x (safe, current). "~> 4.3" gets the latest 4.3.x.
gem "jekyll", "~> 4.3"

group :jekyll_plugins do
  gem "jekyll-feed"          # let Bundler choose a compatible version
  gem "jekyll-paginate"      # classic paginate; fine with Jekyll 4.x
  gem "jekyll-compose"
end

# Ruby 3.x needs webrick for `jekyll serve`
gem "webrick", "~> 1.8", group: :development

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end
gem "wdm", "~> 0.1.1", platforms: [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", platforms: [:jruby]
