source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "jekyll-theme-nickk", path: "../jekyll-theme-nickk"  # sibling theme

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-paginate"
  gem "jekyll-compose"
end

group :development do
  gem "webrick", "~> 1.8"
end
